### ISSUE TITLE
Memory leak when using csv-write-stream?

### ISSUE THREAD

**Issue by iandees** [maxogden/csv-write-stream#21]
Hello! I'm trying to combine `node-osmium` with `csv-write-stream` to dump CSVs of historical OpenStreetMap data. The little node app that I wrote to do this is here:

https://gist.github.com/iandees/f5d2e49b23881e6c0884e254f21ff865

When I run this, memory usage climbs quickly and node dies after ~900k `data` events written on an 8GB EC2 instance. If I remove the CSV writing at [line 17-26](https://gist.github.com/iandees/f5d2e49b23881e6c0884e254f21ff865#file-node-osmium-dumper-js-L17-L26) and just count objects flowing through the system, memory usage stays sane.

I can't imagine such a simple library would have a memory leak. Am I doing something wrong when interacting with this library?

**Comment by mafintosh** [comment]
@iandees the problem is that you are not handling backpressure the correct way. since reading is usually faster than writing we need to pause reading once in a while to not buffer a bunch of stuff in memory. fortunately .pipe on streams does all this for us. the fix for your code is to wrap your logic in a transform stream.

``` js
var stream = new osmium.Stream(reader);
var through = require('through2') // install this from npm

stream.pipe(through.obj(map)).pipe(node_writer)

function map (object, enc, cb) {
  // ... do your stuff here ...
  // afterwards call cb with the object you wanna write to the csv stream
  cb(null, [
        object.id,
        object.version,
        object.visible ? '1' : '0',
        object.changeset,
        object.timestamp().toISOString(),
        object.uid,
        JSON.stringify(object.tags()),
        object.lon ? "(" + object.lon + "," + object.lat + ")" : "NULL"    
  ])
}
```

let me know if this works for you :)

**Comment by iandees** [comment]
Thanks, that helped. I appreciate the time you took to solve this!

**Comment by iandees** [comment]
Ok, this is now definitely off-topic, but one quick question for you @mafintosh:

Ideally I'd like to start a new CSV every 1 million rows. It doesn't appear that [closing the writer and reattaching a new one](https://gist.github.com/iandees/f5d2e49b23881e6c0884e254f21ff865#file-node-osmium-dumper-js-L39-L45) works. How might I take advantage of streams to help me with batching?
