### ISSUE TITLE
Issue with newline characters 

### ISSUE THREAD

**Issue by alexbjorlig** [maxogden/csv-write-stream#25]
How can I write a csv where a newline character does not break the line?

**Comment by notslang** [comment]
A quick test shows that we do this:

``` bash
$ echo '{"test": "some\ntext"}' | csv-write
test
"some
text"
```

...which _looks_ wrong, but it actually gets parsed correctly:

``` bash
$ echo '{"test": "some\ntext"}' | csv-write | csv-parser 
{"test":"some\ntext"}
```

And [RFC 4180](https://tools.ietf.org/html/rfc4180) elaborates on this:

> Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.  For example:
> 
> ``` csv
> "aaa","b CRLF
> bb","ccc" CRLF
> zzz,yyy,xxx
> ```

So double quotes take precedence over line breaks and line breaks don't get escaped.

**Comment by alexbjorlig** [comment]
Thanks for clarifying - it works like a charm.
