### ISSUE TITLE
Callback

### ISSUE THREAD

**Issue by leondroidgeeks** [maxogden/csv-write-stream#32]
Is there any possibility to implement a callback function to continue with the code when writing to file has finished?

**Comment by mafintosh** [comment]
You can listen for `end` to do that

**Comment by leondroidgeeks** [comment]
So you mean `writer.end(callback)?`
Funny, I did that, because I want to send the file after creation has finished
```
writer.end(function() {
            res.set('Content-Type', 'text/csv');
            res.download('exports/' + filename, filename);
          });
```
But I had to set a timeout for res.download otherwise it would send an empty file

**Comment by mafintosh** [comment]
No you need to do

``` js
writer.on('end', function () {
  ...
})
```

Otherwise the stream might not be flushed yet.

For your usecase of piping it to a file you should wait for the last stream in the pipeline to finish though (see mafintosh/pump for help on how to do this)

**Comment by leondroidgeeks** [comment]
I don't know how do exactly use your pump module but this sends an empty file as well

 ```
pump(writer, fs.createWriteStream('exports/' + filename), function(err) {
            console.log('pipe finished', err)
          });
bookings.forEach(function(booking) {
            writer.write(booking);
          });
writer.end();
writer.on('end', function() {
            res.set('Content-Type', 'text/csv');
            res.download('exports/' + filename, filename);
          });
```

**Comment by mafintosh** [comment]
``` js
pump(writer, fs.createWriteStream('exports/' + filename), function(err) {
  console.log('pipe finished', err)
  res.set('Content-Type', 'text/csv');
  res.download('exports/' + filename, filename);
});
```

(you'd prob want to handle pipe errors tho)

**Comment by leondroidgeeks** [comment]
great that worked, thank you very much!
