### ISSUE TITLE
Additional column when first row cell is blank

### ISSUE THREAD

**Issue by hansrq** [maxogden/csv-write-stream#7]
If the first 1 (or more) row cells are blank an additional delimiter will be inserted. This results in one additional column, and all the data being moved, not matching the headers.

Suggested fix:
WriteStream.prototype.serialize = function(row) {
  var str = ''
  for (var i = 0; i < row.length; i++) {
      if(i > 0){
          str += this.separator;
      }
    var cell = row[i]
    if (cell) {
        if (typeof cell !== 'string') cell = cell.toString()
        var needsEscape = false
        if (cell.indexOf('"') > -1) {
            needsEscape = true
            cell = cell.replace(/"/g, '""')
        }
        if (cell.indexOf(this.separator) > -1 || cell.match(/\r?\n/)) {
            needsEscape = true
        }
        if (needsEscape) cell = '"' + cell + '"'
        str += cell;
    }
  }
  return str + this.newline

**Comment by rriemann** [comment]
Has this been integrated? If so, please close the issue. :)
